# Site settings
title: Mahat Hasan
email: "mahatfilms@gmail.com"
description: "Mahat Hasan's Photography Portfolio"
url: "https://MahatPhoto.github.io"   # Your GitHub Pages URL
baseurl: ""                            # Empty for user/organization site
facebook_username: "mathat.photo"
twitter_username: "mahat_hasan"
instagram_username: "mahat.photo"
flickr_username: "mahathasanofficial"
share: true

# Owner/author information
owner:
  name: Mahat Hasan
  avatar: avatar.png
  favicon: favicon.ico
  info: Mahat Hasan's Photography Portfolio

# Settings for comments helper
# Set 'provider' to the comment provider you want to use. (i.e. Disqus, Intense Debate, Livefyre, or Facebook Comments)
# Set 'provider' to false to turn commenting off globally.
comments:
  provider: disqus
  disqus:
    short_name: ""  # Add your Disqus shortname if using comments

# Internal nav
nav:
  - GALLERY: "https://MahatPhoto.github.io/gallery/"  
#  - JOURNAL: "https://MahatPhoto.github.io/journal/"
  - ABOUT: "https://MahatPhoto.github.io/about/"

# All translation keys
translations:
  # 404.html
  permalink: "/404.html"

# Server
destination: ./_site
port: 4000

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
paginate_path: "/journal/page:num/"
permalink: "/journal/:title/"
categories_path: "/journal/category/"
tags_path: "/journal/tag/"
gems:
  - jekyll-paginate
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

# SiteMap
sitemap:
  file: "/sitemap.xml"
  exclude:
    - "/atom.xml"
    - "/feed.xml"
    - "/feed/index.xml"
  include_posts:
    - "/writing/"
  change_frequency_name: "change_frequency"
  priority_name: "priority"
